### PR TITLE
Update Jenkinsfile as of ubports/build-tools@10c0987

### PR DESCRIPTION
**Pull request by UniversalSuperBox**

### CODE REVIEW

**Comment by NeoTheThird** [comment]
'sup with the armhf pr build?

**Comment by UniversalSuperBox** [comment]
Probably something left over in the "PR-2" repository that it's trying to depend on

**Comment by NeoTheThird** [comment]
ah, ffs

**Review by NeoTheThird — APPROVED** [review]
lgtm

**Pull request merged**
